### PR TITLE
fix: autocomplete search-bar flickering

### LINKED ISSUE #372: fix: autocomplete search bar flickering
In desktop screen when user clicks in the autocomplete search bar the transition is not smooth. 

image

further enhancement
reduce the debounce function timer to 300ms.

### PR DESCRIPTION
**Pull request by Shurtu-gal**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #372 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

File: client/src/hooks/useAutoComplete.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ const useAutoComplete = (searchText, limit) => {
   useEffect(() => {
     const timer = setTimeout(() => {
       setSearchKeyword(searchText);
-    }, 800);
+    }, 300);
```
Comment (120EE0692) [inline client/src/hooks/useAutoComplete.js:14]: @Shurtu-gal just do I more addition here when search text length in less than 3 then this should be 10ms.

**Review by 120EE0692 — APPROVED** [review]

File: client/src/pages/live.jsx [hunk 2]
```diff
@@ -74,6 +74,15 @@ const LivePage = () => {
...
 
+export async function getServerSideProps() {
+  return {
+    redirect: {
+      destination: '/comingSoon',
+      permanent: false,
+    },
+  };
+}
+
```
Comment (rutajdash) [inline client/src/pages/live.jsx:85]: Why is this code here?

Comment (Shurtu-gal) [reply client/src/pages/live.jsx]: Due to merging of PR #391.
It has been removed now.

**Review by rutajdash — APPROVED** [review]
