### PR TITLE
fix(photostory): optimise the state update in photostory

### LINKED ISSUE #443: fix(photostory): optimise the state update in photostory
file: [Carousel](https://github.com/Monday-Morning/project-tahiti/blob/main/client/src/components/photostory/Carousel.js)

Do not update the states multiple times by using setLeft, setCurrent and setRight.

### PR DESCRIPTION
**Pull request by Anish-Sarawgi**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #443 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

File: client/src/components/photostory/Carousel.js [hunk 1]
```diff
@@ -13,19 +13,15 @@ const Carousel = ({ content }) => {
   const classes = useStyles();
   const length = content.length;
 
-  const [left, setLeft] = useState(length - 1);
   const [current, setCurrent] = useState(0);
-  const [right, setRight] = useState(1);
+  const left = current === 0 ? length - 1 : current - 1;
+  const right = current === 0 ? length - 1 : current - 1;
```
Comment (120EE0692) [inline client/src/components/photostory/Carousel.js:18]: @Anish-Sarawgi can you please explain the difference between left and right?

Comment (Anish-Sarawgi) [reply client/src/components/photostory/Carousel.js]: Done mistake. Now fixed.
